version: '3.2'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: go_todo_list
      MYSQL_ROOT_PASSWORD: root
      MYSQL_GENERAL_LOG: 0
    volumes:
      - data-mysql:/data/mysql

volumes:
  data-mysql:
